version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - "./db_data:/docker-entrypoint-initdb.d"
    networks:
      - net
    restart: unless-stopped

  www:
    build:
      context: . 
      dockerfile: .devcontainer/php.dockerfile
    container_name: www
    volumes:
      - "./src:/var/www/html"
    ports:
      - 80:80
    depends_on:
      - mysql
    networks:
      - net
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - net

networks:
  net:
    driver: bridge
